set autoread
set clipboard+=unnamedplus
set conceallevel=0
set cursorline
set expandtab
set exrc
set fileencoding=utf-8
set foldmethod=manual
set hidden
set hlsearch
set ignorecase
set mouse=a
set number
set numberwidth=2
set secure
set shiftwidth=2
set showtabline=2
set signcolumn=yes
set smartcase
set smartindent
set tabstop=2
set termguicolors
" set title
set updatetime=300
syntax on
